name: .NET

on:
  workflow_dispatch:
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Dump github context
      run: | 
        echo github context
        tag=$(curl --silent "https://api.github.com/repos/${{ github.event.repository.full_name }}/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')
        echo "LATEST_TAG=${tag}" >> $GITHUB_ENV
        echo "yayy ${tag}"
        echo $LATEST_TAG
    - name: Check
      run: echo "z ${LATEST_TAG}"
