name: Publish Nuget to Github Package

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --no-restore --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release /p:Version=${VERSION}
    - name: Packing
      run: dotnet pack --configuration Release --no-build /p:Version=${VERSION} --output .
    - name: Publishing 
      run: dotnet nuget push ZAP.Commons.${VERSION}.nupkg --source https://nuget.pkg.github.com/zapzombies/index.json --api-key ${{github.token}}
      
