# This is a basic workflow to help you get started with Actions

name: Test Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags: 
      - "v[0-9]+.[0-9]+.[0-9]+.release"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2.3.4
      with: 
        ref: ${{github.ref}}
    - name: List
      run: |
        ls
        echo $PWD
